riter: 100
batch_size: 32
spatial_size: 128
orig_size: 200
log_freq: 10
step_rate: 5e-5
vae_name: camcan_400_Aug_2_100
lr_rate: 1e-4
log_dir: /scratch_net/biwidl214/jonatank/logs/restore/
path: /scratch_net/biwidl214/jonatank/data/dataset_abnormal/new/brats17/
epochs: 500
net_name: train_nn_ssim_30