riter: 10
batch_size: 32
spatial_size: 128
orig_size: 200
log_freq: 10
step_rate: 3e-1
vae_name: camcan_400_Aug_6_100
lr_rate: 1e-2
log_dir: /scratch_net/biwidl214/jonatank/logs/restore/
path: /scratch_net/biwidl214/jonatank/data/dataset_abnormal/new/brats17/
epochs: 201
