riter: 200
batch_size: 32
spatial_size: 128
orig_size: 200
log_freq: 20
step_rate: 0.003
vae_name: camcan_400_Aug_6_100
weight: 2
log_dir: /scratch_net/biwidl214/jonatank/logs/restore/
path: /scratch_net/biwidl214/jonatank/data/dataset_abnormal/new/brats17/